---
output: rmarkdown::github_document
---
# jointHWGraph: Bayesian joint Gaussian garphical model estimation with joint hierarchical Wishart priors.

## Installation
```r

install.packages("devtools")
install.packages("remotes")
install.packages("fdrtool")
install.packages("Rcpp")
install.packages("RcppParallel")

library(devtools)
library(remotes)

remotes::install_github("AapoKorhonen/jointHWGraph")

library(fdrtool)
library(jointHWGraph)

```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Example


```{r, echo=TRUE,results="hide", fig.keep='all', warning=FALSE}

library(jointHWGraph)
set.seed(42)
data_sim <- group_data_generator(n=100, p=100, number_of_groups = 3, similarity = 0.9)

results  = jointHWGraph(data_sim$data)

#install.packages("qgraph")
library(qgraph)

par(mfrow=c(1,3))
qgraph(results$adjacency_matrices[[1]], title = "Group 1 network", labels=F,usePCH=T)
qgraph(results$adjacency_matrices[[2]], title = "Group 2 network", labels=F,usePCH=T)
qgraph(results$adjacency_matrices[[3]], title = "Group 3 network", labels=F,usePCH=T)


```



## Example with breast cancer dataset 


```{r, echo=TRUE,results="hide", fig.keep='all', warning=FALSE}

#devtools::install_github("Zhangxf-ccnu/JEGN", subdir="pkg")
library(JEGN)

data("TCGA.BRCA")
TCGA.BRCA$Datatype
dat1 <- TCGA.BRCA$X[2,1][[1]]
dat2 <- TCGA.BRCA$X[2,2][[1]]
dat3 <- TCGA.BRCA$X[2,3][[1]]
dat4 <- TCGA.BRCA$X[2,4][[1]]

data_list <- list( dat1,dat2,dat3,dat4) 

library(jointHWGraph)

results <- jointHWGraph(data_list)


ad1 <- results$adjacency_matrices[[1]]
colnames(ad1) <-  colnames(dat1)
ad2 <- results$adjacency_matrices[[2]]
colnames(ad2) <-  colnames(dat1)
ad3 <- results$adjacency_matrices[[3]]
colnames(ad3) <-  colnames(dat1)
ad4 <- results$adjacency_matrices[[4]]
colnames(ad4) <-  colnames(dat1)


par(mfrow=c(2,2))
qgraph::qgraph(ad1,labels = F,
              title ="Luminal A",usePCH=T,vsize= 3)
qgraph::qgraph(ad2,labels = F,
               title ="Luminal B",usePCH=T,vsize= 3)
qgraph::qgraph(ad3,labels = F,
               title ="HER2-enriched",usePCH=T,vsize= 3)
qgraph::qgraph(ad4,labels = F,
               title ="Basal-like",usePCH=T,vsize= 3)

only1 <- abs(ad1 - ad1*ad2*ad3*ad4)
only2 <- abs(ad2 - ad1*ad2*ad3*ad4)
only3 <- abs(ad3 - ad1*ad2*ad3*ad4)
only4 <- abs(ad4 - ad1*ad2*ad3*ad4)


par(mfrow=c(2,2))
qgraph::qgraph(only1[colSums(only1)>0, colSums(only1)>0],labels = colnames(only1[colSums(only1)>0, colSums(only1)>0]),
              title ="Luminal A, unique connections",usePCH=T,vsize= 5,borders = FALSE,label.cex = 2)
qgraph::qgraph(only2[colSums(only2)>0, colSums(only2)>0],labels = colnames(only2[colSums(only2)>0, colSums(only2)>0]),
               title ="Luminal B, unique connections",usePCH=T,vsize= 5,borders = FALSE,label.cex = 2)
qgraph::qgraph(only3[colSums(only3)>0, colSums(only3)>0],labels = colnames(only3[colSums(only3)>0, colSums(only3)>0]),
               title ="HER2-enriched, unique connections",usePCH=T,vsize= 5,borders = FALSE,label.cex = 2)
qgraph::qgraph(only4[colSums(only4)>0, colSums(only4)>0],labels = colnames(only4[colSums(only4)>0, colSums(only4)>0]),
               title ="Basal-like, unique connections",usePCH=T,vsize= 5,borders = FALSE,label.cex = 2)

```